trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    docker run -d \
    --net host \
    --name ipfs \
    node:latest sleep infinity
    docker exec ipfs bash -c \
      "git clone https://github.com/ipfs/js-ipfs.git \
      && cd js-ipfs \
      && npm install --unsafe-perm \
      && ./packages/ipfs/src/cli/bin.js init \
      && ./packages/ipfs/src/cli/bin.js config --json libp2p.config.dht.enabled true \
      && bash -c './packages/ipfs/src/cli/bin.js daemon &'"
  displayName: 'Run ipfs daemon'

- script: |
    docker run -d \
    --net host \
    --name orbit-db-http-api \
    -e IPFS_HOST='localhost' \
    -e IPFS_PORT=5002 \
    -e LOG='DEBUG' \
    -e FORCE_HTTP1=true \
    $(API_Image_Name):$(API_Image_Branch) src/cli.js api --debug
  displayName: 'Run orbit-db-http-api server'

- script: |
    local tests_exit_code
    docker run --rm \
    --net host \
    -e ORBIT_DB_HTTP_API_URL='http://localhost:3000' \
    phillmac/py-orbit-db-http-client-dev python /py-orbit-db-http-client/tests/test.py
    tests_exit_code=$?
    docker stop ipfs orbit-db-http-api
    docker logs orbit-db-http-api
    docker logs ipfs
    exit $tests_exit_code
    
  displayName: 'Run orbit-db-http-client tests'
